services:
  postgres:
    container_name: recomenda_cine
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
volumes:
    data: