services:
  spring:
    container_name: spring
    build: ./
    ports:
      - 8080:8080
    networks:
      - backend-network
    restart: always 
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db  
    ports:
      - 5432:5432
    networks:
      - backend-network
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge