spring:
    application:
        name: backend

# PostgreSQl
    datasource:
            url: jdbc:h2:mem:api 
            username: admin
            password: 
    jpa: 
        hibernate:
            ddl-auto: update
    flyway:
        enabled: true
        locations: classpath:db/migration
api:
  security:
        token:
            secret: ${JTW_SECRET:my-secret-key}

admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}